# Numpy Indexing and Slicing

In [1]:
import numpy as np

In [2]:
# creata an array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
a[1:5]

array([2, 3, 4, 5])

In [4]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [5]:
b[2]

4

In [6]:
c = b.reshape(3, 2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [7]:
c[0]

array([0, 2])

In [8]:
c[(c < 5) | (c > 7)]

array([ 0,  2,  4,  8, 10])

## Enlist boolean operators conditional operators?



---
# Making an array from a data or another array

In [9]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [10]:
len(a)

45

In [11]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [12]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [13]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

---
# Matrix or Matrices

In [16]:
# create a 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a[1]

array([4, 5, 6])

In [18]:
# create a matrix
b = np.arange(0, 100, 2).reshape(5,10)
b 

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [19]:
# slicing a matrix of 3x2
c = b[0:3,3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [20]:
b.max()

98

In [21]:
b.min()

0

In [22]:
b.sum()

2450

In [23]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [24]:
b.max(axis=0) # only for column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [25]:
b.max(axis=1) # only for row

array([18, 38, 58, 78, 98])

In [26]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [27]:
m * np.array([20, 22])

array([[  0,  44],
       [ 80, 132],
       [160, 220],
       [240, 308],
       [320, 396]])

In [28]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [29]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [30]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])